services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV = production
    networks:
      - app7
    depends_on:
      - sgbd
  mongo:
    image: "mongo:latest"
    ports:
      - "3005:27017"
    volumes:
      - data:/data/db
    networks:
      - app7

volumes:
  data:

networks:
  app7:
